"""goated

Revision ID: f09ca36d9397
Revises: 14e7ad8b7d1b
Create Date: 2023-05-10 02:01:42.804768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f09ca36d9397'
down_revision = '14e7ad8b7d1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('total', sa.Float(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email')

    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_column('total')
        batch_op.drop_column('item')

    op.drop_table('reviews')
    # ### end Alembic commands ###
